### ISSUE TITLE
Resource adaptors configuration change exception

### ISSUE THREAD

**Issue by SergeyLee** [RestComm/jain-slee#15]
From ticket 32923:

We are trying to change the RA entity configuration properties using GUI interface (this example is for HttpServletRA mobicents-slee-ra-http-servlet-DU-6.1.5.GA-TelScale, but the same problem we have also with other RAs - ex. SIP RA);

15:15:39:209 [INFO] Entity HttpServletRA activated
15:15:58:701 [INFO] Entity HttpServletRA deactivated
**15:16:40:709 [ERROR] the property HTTP_REQUEST_TIMEOUT has null value**
Check the JAIN SLEE logs for more detailed information about this error.

**Comment by SergeyLee** [comment]
Logs on this case:

> 15:49:25,312 ERROR [STDERR] (http-127.0.0.1-8080-1) Caused by: javax.slee.resource.InvalidConfigurationException: the property name has null value
> 15:49:25,312 ERROR [STDERR] (http-127.0.0.1-8080-1) 	at org.mobicents.slee.resource.ResourceAdaptorObjectImpl.verifyConfigProperties(ResourceAdaptorObjectImpl.java:231)
> 15:49:25,312 ERROR [STDERR] (http-127.0.0.1-8080-1) 	at org.mobicents.slee.resource.ResourceAdaptorObjectImpl.raConfigurationUpdate(ResourceAdaptorObjectImpl.java:198)
> 15:49:25,312 ERROR [STDERR] (http-127.0.0.1-8080-1) 	at org.mobicents.slee.resource.ResourceAdaptorEntityImpl.updateConfigurationProperties(ResourceAdaptorEntityImpl.java:274)
> 15:49:25,312 ERROR [STDERR] (http-127.0.0.1-8080-1) 	at org.mobicents.slee.container.management.ResourceManagementImpl.updateConfigurationProperties(ResourceManagementImpl.java:429)
> 15:49:25,312 ERROR [STDERR] (http-127.0.0.1-8080-1) 	at org.mobicents.slee.container.management.jmx.ResourceManagementMBeanImpl.updateConfigurationProperties(ResourceManagementMBeanImpl.java:166)

and:

> 15:49:25,310 ERROR [STDERR] (http-127.0.0.1-8080-1) 	at org.mobicents.slee.container.management.console.server.mbeans.ResourceManagementMBeanUtils.updateConfigurationProperties(ResourceManagementMBeanUtils.java:237)
> 15:49:25,310 ERROR [STDERR] (http-127.0.0.1-8080-1) 	at org.mobicents.slee.container.management.console.server.resources.ResourceServiceImpl.setResourceAdaptorEntityConfigurationProperties(ResourceServiceImpl.java:109)

**Comment by SergeyLee** [comment]
bug is here
https://github.com/RestComm/jain-slee/blob/2.x/tools/slee-management-console/server/src/main/java/org/mobicents/slee/container/management/console/server/PropertiesInfoUtils.java#L56

I fix it with
String value = propertiesInfo.getProperty(key);

but for HTTP Servlet... update configuration is not available:
https://github.com/RestComm/jain-slee.http/blob/master/resources/http-servlet/ra/src/main/java/org/mobicents/slee/resource/http/HttpServletResourceAdaptor.java#L238
