### ISSUE TITLE
[Twiddle] Command failure - "--nsrc" argument not detected

### ISSUE THREAD

**Issue by tzieleniewski** [RestComm/jain-slee#21]
Hi,

When invoking the following twiddle command I get the following error.
The --nsrc argument is provided but Twiddle compains.

```
./twiddle.sh trace -g --nsrc=SbbNotification[service=ServiceID[name=...],sbb=SbbID[name=...]] --name=error        
14:18:37,698 ERROR [Twiddle] Command failure
org.jboss.console.twiddle.command.CommandException: Operation "getTraceLevel" for command: "trace", found unexpected opt: --nsrc=SbbNotification[service=ServiceID[name=...],sbb=SbbID[name=...]]
        at org.mobicents.tools.twiddle.jslee.TraceCommand$GetLevelOperation.buildOperation(TraceCommand.java:383)
        at org.mobicents.tools.twiddle.jslee.TraceCommand.processArguments(TraceCommand.java:177)
        at org.mobicents.tools.twiddle.AbstractSleeCommand.execute(AbstractSleeCommand.java:114)
        at org.jboss.console.twiddle.Twiddle.main(Twiddle.java:306)
```

Regards
Tomasz Krzysztof Zieleniewski

**Comment by SergeyLee** [comment]
Hi @tzieleniewski 
I have fixed this issue!
Take care!
