### ISSUE TITLE
Slee create multiple transaction in the same thread

### ISSUE THREAD

**Issue by nhanth87** [RestComm/jain-slee#5]
Slee create multiple transaction in the same thread and caught error exception:

20:35:44,230 ERROR [AFPSbbImpl] (pool-28-thread-2) Exception
javax.transaction.NotSupportedException: BaseTransaction.checkTransactionState - [com.arjuna.ats.internal.jta.transaction.arjunacore.alreadyassociated] [com.arjuna.ats.internal.jta.transaction.arjunacore.alreadyassociated] thread is already associated with a transaction!
at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.begin(BaseTransaction.java:80)
at com.arjuna.ats.jbossatx.BaseTransactionManagerDelegate.begin(BaseTransactionManagerDelegate.java:65)
at org.mobicents.slee.runtime.transaction.SleeTransactionManagerImpl.beginSleeTransaction(SleeTransactionManagerImpl.java:251)
at org.mobicents.slee.runtime.transaction.SleeTransactionManagerImpl.beginSleeTransaction(SleeTransactionManagerImpl.java:61)
at com.kalsym.afp.DatabasePool$1.executeSimple(DatabasePool.java:40)
at org.mobicents.slee.resource.jdbc.task.simple.SimpleJdbcTask.execute(SimpleJdbcTask.java:19)
at org.mobicents.slee.resource.jdbc.JdbcResourceAdaptor$1.run(JdbcResourceAdaptor.java:387)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
20:35:44,230 WARN [arjLoggerI18N] (pool-28-thread-2) [com.arjuna.ats.arjuna.coordinator.BasicAction_40] - Abort called on already aborted atomic action 7f000001:cbe5:569f7592:724

**Comment by nhanth87** [comment]
Jainslee should check is there transaction assoc with this thread but difference status before create new one.
If already have transaction then change status to active

**Comment by deruelle** [comment]
Can you attach logs (if no confidential inform$ation in them) and investigate this issue to propose a fix ?

**Comment by SergeyLee** [comment]
I need origin of this issue: tickets or google-groups topic.

**Comment by SergeyLee** [comment]
I found this JBoss bug:
[Dirty transaction remains if rollback failed](https://issues.jboss.org/browse/JBTM-751)

and here: https://github.com/RestComm/jain-slee.jdbc/blob/master/resources/jdbc/ra/src/main/java/org/mobicents/slee/resource/jdbc/JdbcResourceAdaptor.java#L412-L421

i added in this catch:
```
try {
	//rolling back transaction if failed
	if (txManager.getTransaction() != null) {
		txManager.rollback();
	}
}
catch (Exception e1) {
	tracer.fine(
			"failure in transaction rollback", e1);
}
```

**Comment by nhanth87** [comment]
It's hard to reproduce, and it good if you add some debug info.
Next time when it happen again, you will know the root cause

**Comment by SergeyLee** [comment]
I added Pull Request in jain-slee.jdbc repo:
https://github.com/RestComm/jain-slee.jdbc/pull/2
