### ISSUE TITLE
Size limit? when firing SLEE events

### ISSUE THREAD

**Issue by slhayden** [RestComm/jain-slee#6]
public void fireEvent(Object event, EventTypeID eventType, ExternalActivityHandle handle, Address address)

**When invoking this method with an Object event with a serialized size > 1k, the receiving end throws an exception**:

java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor290.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.mobicents.slee.container.rmi.RMIServerImpl.invoke(RMIServerImpl.java:94)
        at sun.reflect.GeneratedMethodAccessor281.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:305)
        at sun.rmi.transport.Transport$1.run(Transport.java:159)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:155)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:535)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:790)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:649)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:662)
Caused by: java.rmi.RemoteException: Failed to fire event due to:; nested exception is:
        java.io.StreamCorruptedException: invalid type code: 00
        at org.mobicents.slee.connector.remote.RemoteSleeConnectionServiceImpl.fireEvent(RemoteSleeConnectionServiceImpl.java:101)
        ... 17 more
Caused by: java.io.StreamCorruptedException: invalid type code: 00
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1355)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1946)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1870)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1752)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:350)
        at org.mobicents.slee.connector.remote.RemoteEventWrapper.getEvent(RemoteEventWrapper.java:71)
        at org.mobicents.slee.connector.remote.RemoteSleeConnectionServiceImpl.fireEvent(RemoteSleeConnectionServiceImpl.java:98)

**The Sender gets this exception**

Caused by: java.rmi.RemoteException: Failed to fire event due to:; nested exception is:
        java.io.StreamCorruptedException: invalid type code: 00
        at org.mobicents.slee.connector.remote.RemoteSleeConnectionServiceImpl.fireEvent(RemoteSleeConnectionServiceImpl.java:101) [:2.7.0.FINAL]
        at sun.reflect.GeneratedMethodAccessor290.invoke(Unknown Source) [:1.6.0_26]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_26]
        at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_26]
        at org.mobicents.slee.container.rmi.RMIServerImpl.invoke(RMIServerImpl.java:94) [:2.7.0.FINAL]
        at sun.reflect.GeneratedMethodAccessor281.invoke(Unknown Source) [:1.6.0_26]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_26]
        at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_26]
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:305) [:1.6.0_26]
        at sun.rmi.transport.Transport$1.run(Transport.java:159) [:1.6.0_26]
        at java.security.AccessController.doPrivileged(Native Method) [:1.6.0_26]
        at sun.rmi.transport.Transport.serviceCall(Transport.java:155) [:1.6.0_26]
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:535) [:1.6.0_26]
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:790) [:1.6.0_26]
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:649) [:1.6.0_26]
        ... 3 more
Caused by: java.io.StreamCorruptedException: invalid type code: 00
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1355) [:1.6.0_26]
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1946) [:1.6.0_26]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1870) [:1.6.0_26]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1752) [:1.6.0_26]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328) [:1.6.0_26]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:350) [:1.6.0_26]
        at org.mobicents.slee.connector.remote.RemoteEventWrapper.getEvent(RemoteEventWrapper.java:71) [:2.7.0.FINAL]
        at org.mobicents.slee.connector.remote.RemoteSleeConnectionServiceImpl.fireEvent(RemoteSleeConnectionServiceImpl.java:98) [:2.7.0.FINAL]
        ... 17 more

**Comment by slhayden** [comment]
Confirmed bug on JainSlee 2.8.

In class RemoteEventWrapper (jain-slee/container/remote/src/main/java/org/mobicents/slee/connector/remote/RemoteEventWrapper.java), the readExternal() method calls in.read().  This method does not guarantee to fill the byte buffer:

from java docs:  read() This method will block until **some** input is available.  If the byte buffer is too long to be transmitted in one packet, this read() should be done in a loop.

I suggest changing this method to **readFully()** instead which corrected the problem for me.
It might also be suggested to add a flush on the writeExternal() and a serialVersionUID method for completeness.

Attached is a patch file.
[RemoteEventWrapper.patch.zip](https://github.com/RestComm/jain-slee/files/126660/RemoteEventWrapper.patch.zip)

**Comment by nhanth87** [comment]
It's great contribution, slhayden.
Please fork restcomm jainslee to your repo, make fix and create pull request. 
That make easy for review and named your contribution

**Comment by deruelle** [comment]
@slhayden Thanks. @nhanth87 is right, can you do a pull request instead ? 

You can read more about how to contribute in reading the Section [Development Process of our Open Source Playbook](https://docs.google.com/document/d/1RZz2nd2ivCK_rg1vKX9ansgNF6NpK_PZl81GxZ2MSnM/edit#heading=h.mcjitemt6ng1)

**Comment by slhayden** [comment]
No problem, I’ll get that submitted really soon.


On Feb 11, 2016, at 10:26 AM, Jean Deruelle <notifications@github.com<mailto:notifications@github.com>> wrote:


@slhayden<https://github.com/slhayden> Thanks. @nhanth87<https://github.com/nhanth87> is right, can you do a pull request instead ?

You can read more about how to contribute in reading the Section Development Process of our Open Source Playbook<https://docs.google.com/document/d/1RZz2nd2ivCK_rg1vKX9ansgNF6NpK_PZl81GxZ2MSnM/edit#heading=h.mcjitemt6ng1>

**Comment by deruelle** [comment]
Great. Can you also sign the Contributor License Agreement at http://www.telestax.com/open-source/#Contribute ?
